# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "VagrantVM"
    vb.gui = false
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.hostname = "VagrantVM"

  config.vm.provision "file", source: "../src/docker-compose.yml", destination: "/home/vagrant/app/docker-compose.yml"
  config.vm.provision "file", source: "../src/services", destination: "/home/vagrant/app/services"

end