# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # manager01
  config.vm.define "manager01" do |manager01|
    manager01.vm.hostname = "manager01"
    manager01.vm.network "private_network", ip: "192.168.10.100"

    manager01.vm.provision "file", source: "../src/nginx/nginx.conf", destination: "/home/vagrant/app/nginx/nginx.conf"
    manager01.vm.provision "file", source: "../src/nginx/wait-for-it.sh", destination: "/home/vagrant/app/nginx/wait-for-it.sh"

    manager01.vm.provision "shell", inline: "chmod +x /home/vagrant/app/nginx/wait-for-it.sh"

    manager01.vm.provision "file", source: "../src/docker-compose.yml", destination: "/home/vagrant/app/docker-compose.yml"
    manager01.vm.provision "file", source: "../src/services", destination: "/home/vagrant/app/services"

    manager01.vm.provision "shell", path: "./scripts/install_docker.sh"
    manager01.vm.provision "shell", path: "./scripts/init_swarm.sh", args: "manager"

    manager01.vm.provision "final_deploy", type: "shell", path: "./scripts/deploy_swarm.sh", run: "never"

    manager01.vm.provider "virtualbox" do |vb|
      vb.name = "manager01_vm"
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  # worker01
  config.vm.define "worker01" do |worker01|
    worker01.vm.hostname = "worker01"
    worker01.vm.network "private_network", ip: "192.168.10.101"

    worker01.vm.provision "shell", path: "./scripts/install_docker.sh"
    worker01.vm.provision "shell", path: "./scripts/init_swarm.sh", args: "worker"

    worker01.vm.provider "virtualbox" do |vb|
      vb.name = "worker01_vm"
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  # worker02
  config.vm.define "worker02" do |worker02|
    worker02.vm.hostname = "worker02"
    worker02.vm.network "private_network", ip: "192.168.10.102"

    worker02.vm.provision "shell", path: "./scripts/install_docker.sh"
    worker02.vm.provision "shell", path: "./scripts/init_swarm.sh", args: "worker"

    worker02.vm.provider "virtualbox" do |vb|
      vb.name = "worker02_vm"
      vb.memory = 2048
      vb.cpus = 1
    end
  end

  config.trigger.after :up do |trigger|
    trigger.name = "Launch Docker Stack Deploy"

    trigger.only_on = "worker02"

    trigger.run = {
      inline: "vagrant provision manager01 --provision-with final_deploy"
    }
  end
end